[package]
name = "trapped-knight"
version = "0.1.0"
authors = ["Chris Evans <git@cevans.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
